"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add parent directory to Python path so we can import from common
sys.path.insert(0, str(BASE_DIR.parent))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-r(bcn+trm#9^(jpiq8wj9l^)_l5#vz&x1^un@!-w@_k-70c(-)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Domain configuration from environment
APPLICATION_SET_DOMAIN = os.environ.get("APPLICATION_SET_DOMAIN", "vfservices.viloforge.com")

ALLOWED_HOSTS = [
    f"billing.{APPLICATION_SET_DOMAIN}",
    f".{APPLICATION_SET_DOMAIN}",
    "localhost",
    "127.0.0.1",
    "[::1]",
    "billing-api"
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_extensions",
    "corsheaders",
    "billing",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "common.jwt_auth.middleware.JWTAuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "vfdb"),
        "USER": os.environ.get("POSTGRES_USER", "vfuser"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "vfpass"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# JWT configuration
JWT_SECRET = os.environ.get("VF_JWT_SECRET", "change-me")
SSO_COOKIE_DOMAIN = os.environ.get("SSO_COOKIE_DOMAIN", "localhost")
DEFAULT_REDIRECT_URL = os.environ.get("DEFAULT_REDIRECT_URL", "/")

# Logging configuration
LOG_BASE_DIR = os.environ.get("LOG_BASE_DIR", "/tmp")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {module} {funcName} {lineno} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
        "detailed": {
            "format": "[{asctime}] {levelname} {name} - {module}.{funcName}:{lineno} - {message}",
            "style": "{",
        },
        "api": {
            "format": "[{asctime}] {levelname} BILLING-API - {name} - {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "detailed",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_BASE_DIR, "billing_api.log"),
            "formatter": "verbose",
            "maxBytes": 10485760,  # 10MB
            "backupCount": 5,
        },
        "debug_console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "detailed",
            "filters": ["require_debug_true"],
        },
        "debug_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_BASE_DIR, "billing_api_debug.log"),
            "formatter": "verbose",
            "filters": ["require_debug_true"],
            "maxBytes": 10485760,  # 10MB
            "backupCount": 3,
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_BASE_DIR, "billing_api_errors.log"),
            "formatter": "verbose",
            "maxBytes": 5242880,  # 5MB
            "backupCount": 10,
        },
        "api_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_BASE_DIR, "billing_api_requests.log"),
            "formatter": "api",
            "maxBytes": 10485760,  # 10MB
            "backupCount": 5,
        },
        "security_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler", 
            "filename": os.path.join(LOG_BASE_DIR, "billing_api_security.log"),
            "formatter": "verbose",
            "maxBytes": 5242880,  # 5MB
            "backupCount": 10,
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "error_file", "api_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console", "error_file", "security_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["debug_console", "debug_file"],
            "level": "DEBUG" if DEBUG else "WARNING",
            "propagate": False,
        },
        # Main project loggers
        "main": {
            "handlers": ["console", "file", "debug_console", "debug_file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        # Billing app loggers
        "billing": {
            "handlers": ["console", "file", "debug_console", "debug_file", "api_file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "billing.views": {
            "handlers": ["console", "file", "debug_console", "debug_file", "api_file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "billing.models": {
            "handlers": ["console", "file", "debug_console", "debug_file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        # JWT Auth logger
        "common.jwt_auth": {
            "handlers": ["console", "file", "security_file"],
            "level": "INFO",
            "propagate": False,
        },
        # API-specific loggers
        "billing.api": {
            "handlers": ["console", "file", "api_file"],
            "level": "INFO",
            "propagate": False,
        },
        "billing.security": {
            "handlers": ["console", "file", "error_file", "security_file"],
            "level": "INFO",
            "propagate": False,
        },
        "billing.performance": {
            "handlers": ["console", "debug_file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        # REST Framework logging
        "rest_framework": {
            "handlers": ["console", "file", "api_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# CORS configuration for Traefik routing
CORS_ALLOWED_ORIGINS = [
    f"https://website.{APPLICATION_SET_DOMAIN}",
    f"https://{APPLICATION_SET_DOMAIN}",
    "http://localhost:3000",  # Development
    "http://localhost:8080",  # Development
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Redis configuration for RBAC-ABAC
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.environ.get('REDIS_PORT', 6379))

# Service name for RBAC-ABAC
SERVICE_NAME = 'billing_api'

# RBAC-ABAC Cache settings
RBAC_ABAC_CACHE_TTL = int(os.environ.get('RBAC_ABAC_CACHE_TTL', 86400))  # Default 24 hours
IDENTITY_PROVIDER_URL = os.environ.get('IDENTITY_PROVIDER_URL', 'http://identity-provider:8000')
